### import dependencies

In [46]:
import pandas as pd
import numpy as np
import seaborn as sns
from sklearn.preprocessing import LabelEncoder,OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.linear_model import LinearRegression

### read csv

In [68]:
df = pd.read_csv("assets/carprices.csv", names=["model","mileage","price","age"],header=0)

In [69]:
df.head(8)

model  mileage  price  age
0   BMW X5    69000  18000    6
1   BMW X5    35000  34000    3
2   BMW X5    57000  26100    5
3   BMW X5    22500  40000    2
4   BMW X5    46000  31500    4
5  Audi A5    59000  29400    5
6  Audi A5    52000  32000    5
7  Audi A5    72000  19300    6

In [70]:
df.model.unique()

array(['BMW X5', 'Audi A5', 'Mercedez Benz C class'], dtype=object)

### label the text to numaric

In [71]:
labelEncoder = LabelEncoder()

In [72]:
df.model = labelEncoder.fit_transform(df.model)

In [73]:
df.model.unique()

array([1, 0, 2])

In [74]:
X = df.drop(["price"],axis=1)
y = df.price

In [75]:
ohe = OneHotEncoder()

In [76]:
ct = ColumnTransformer([("model",ohe,[0])],remainder="passthrough")

In [77]:
X = ct.fit_transform(X)

In [78]:
X= X[:,1:]

In [79]:
lr = LinearRegression()

In [80]:
lr.fit(X,y)

LinearRegression()

In [81]:
X

array([[1.00e+00, 0.00e+00, 6.90e+04, 6.00e+00],
       [1.00e+00, 0.00e+00, 3.50e+04, 3.00e+00],
       [1.00e+00, 0.00e+00, 5.70e+04, 5.00e+00],
       [1.00e+00, 0.00e+00, 2.25e+04, 2.00e+00],
       [1.00e+00, 0.00e+00, 4.60e+04, 4.00e+00],
       [0.00e+00, 0.00e+00, 5.90e+04, 5.00e+00],
       [0.00e+00, 0.00e+00, 5.20e+04, 5.00e+00],
       [0.00e+00, 0.00e+00, 7.20e+04, 6.00e+00],
       [0.00e+00, 0.00e+00, 9.10e+04, 8.00e+00],
       [0.00e+00, 1.00e+00, 6.70e+04, 6.00e+00],
       [0.00e+00, 1.00e+00, 8.30e+04, 7.00e+00],
       [0.00e+00, 1.00e+00, 7.90e+04, 7.00e+00],
       [0.00e+00, 1.00e+00, 5.90e+04, 5.00e+00]])

<b>Price of mercedez benz that is 4 yr old with mileage 45000</b>

In [65]:
lr.predict([[0,1,45000,4]])

array([36991.31721062])

<b>Price of BMW X5 that is 7 yr old with mileage 86000</b>

In [83]:
lr.predict([[1,0,86000,7]])

array([11080.74313219])